#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# bp_fpga_arty_a7_100t.tcl: Tcl script for re-creating project 'bp_fpga_arty_a7_100t'
#
# Generated by Vivado on Sat Feb 27 16:02:57 -0800 2021
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (bp_fpga_arty_a7_100t.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_fp_to_rec.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_rec_to_fp.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_regfile.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_scoreboard.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_complex.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_tile_node.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_alu.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_arbitrate.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_branch.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir_lru_extract.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir_tag_checker.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_gad.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_decode.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_predecode.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_stall.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_pending_bits.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_pma.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_spec_bits.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_core_complex.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_bht.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_btb.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_instr_scan.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_complex.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_tile_node.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_l2e_tile_node.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_addr_to_cce_id.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_id_to_cord.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cord_to_id.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_lce_id_to_cord.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_mem_complex.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bp_mmu.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_multicore.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_nd_socket.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bp_pma.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_complex.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_tile_node.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_tile_node.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bp_tlb.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bsg_async_noc_link.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bsg_bus_pack.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bsg_fifo_1r1w_rolly.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_top.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_ptw.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_scheduler.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_director.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_dcache/bp_be_dcache.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_detector.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_csr.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_pc_gen.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_top.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_icache.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cache_slice.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_loopback.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_msg.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_burst_to_lite.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cce_to_cache_dma.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_io_cce.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_lite_to_stream.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_src_sel.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/lce/bp_lce.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_lite_to_burst.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_uce.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/lce/bp_lce_cmd.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_ram.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cce_to_cache.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir_segment.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_fsm.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/lce/bp_lce_req.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_to_mem_link_bidir.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_fsm_top.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_stream_to_lite.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_wrapper.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_reg.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cache_dma_to_cce.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cfg.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_core.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_clint_slice.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_tile.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_link_to_lce.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_vdp.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_tile.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_core_minimal.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_l2e_tile.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_tile.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_vdp.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_unicore.sv"
#    "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_tile.sv"
#    "C:/Users/kaeli/repos/black-parrot/fpga/arty_a7_100t/arty_a7_100.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_fp_to_rec.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_rec_to_fp.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_regfile.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_scoreboard.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_complex.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_tile_node.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_alu.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_arbitrate.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_branch.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir_lru_extract.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir_tag_checker.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_gad.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_decode.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_predecode.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_stall.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_pending_bits.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_pma.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_spec_bits.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_core_complex.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_bht.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_btb.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_instr_scan.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_complex.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_tile_node.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_l2e_tile_node.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_addr_to_cce_id.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_id_to_cord.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cord_to_id.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_lce_id_to_cord.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_mem_complex.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bp_mmu.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_multicore.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_nd_socket.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bp_pma.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_complex.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_tile_node.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_tile_node.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bp_tlb.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bsg_async_noc_link.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bsg_bus_pack.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_common/src/v/bsg_fifo_1r1w_rolly.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_top.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_ptw.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_scheduler.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_director.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_dcache/bp_be_dcache.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_detector.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_calculator/bp_be_csr.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_pc_gen.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_top.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_fe/src/v/bp_fe_icache.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cache_slice.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_loopback.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_msg.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_burst_to_lite.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cce_to_cache_dma.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_io_cce.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_lite_to_stream.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_src_sel.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/lce/bp_lce.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_lite_to_burst.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_uce.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/lce/bp_lce_cmd.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_inst_ram.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cce_to_cache.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_dir_segment.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_fsm.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/lce/bp_lce_req.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_me_cce_to_mem_link_bidir.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_fsm_top.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/wormhole/bp_stream_to_lite.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_wrapper.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce_reg.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cache/bp_me_cache_dma_to_cce.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_me/src/v/cce/bp_cce.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cfg.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_core.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_clint_slice.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_tile.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_link_to_lce.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_cacc_vdp.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_io_tile.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_core_minimal.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_l2e_tile.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_tile.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_vdp.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_unicore.sv" \
   "C:/Users/kaeli/repos/black-parrot/bp_top/src/v/bp_sacc_tile.sv" \
   "C:/Users/kaeli/repos/black-parrot/fpga/arty_a7_100t/arty_a7_100.xdc" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "bp_fpga_arty_a7_100t"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "bp_fpga_arty_a7_100t.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../../vivado-test-projects/bp_fpga_arty_a7_100t"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../../../AppData/Roaming/Xilinx/Vivado/2020.2/xhub/board_store/xilinx_board_store"]" -objects $obj
set_property -name "board_part" -value "digilentinc.com:arty-a7-100:part0:1.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "arty-a7-100" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_fp_to_rec.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_rec_to_fp.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_checker/bp_be_regfile.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_checker/bp_be_scoreboard.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_cacc_complex.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_cacc_tile_node.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_alu.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_arbitrate.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_branch.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_dir_lru_extract.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_dir_tag_checker.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_gad.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_inst_decode.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_inst_predecode.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_inst_stall.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_pending_bits.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_pma.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_spec_bits.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_core_complex.sv"] \
 [file normalize "${origin_dir}/../../bp_fe/src/v/bp_fe_bht.sv"] \
 [file normalize "${origin_dir}/../../bp_fe/src/v/bp_fe_btb.sv"] \
 [file normalize "${origin_dir}/../../bp_fe/src/v/bp_fe_instr_scan.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_io_complex.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_io_tile_node.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_l2e_tile_node.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_addr_to_cce_id.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_cce_id_to_cord.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_cord_to_id.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_lce_id_to_cord.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_mem_complex.sv"] \
 [file normalize "${origin_dir}/../../bp_common/src/v/bp_mmu.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_multicore.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_nd_socket.sv"] \
 [file normalize "${origin_dir}/../../bp_common/src/v/bp_pma.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_sacc_complex.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_sacc_tile_node.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_tile_node.sv"] \
 [file normalize "${origin_dir}/../../bp_common/src/v/bp_tlb.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bsg_async_noc_link.sv"] \
 [file normalize "${origin_dir}/../../bp_common/src/v/bsg_bus_pack.sv"] \
 [file normalize "${origin_dir}/../../bp_common/src/v/bsg_fifo_1r1w_rolly.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_top.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_ptw.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_checker/bp_be_scheduler.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_checker/bp_be_director.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_dcache/bp_be_dcache.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_checker/bp_be_detector.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_calculator/bp_be_csr.sv"] \
 [file normalize "${origin_dir}/../../bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv"] \
 [file normalize "${origin_dir}/../../bp_fe/src/v/bp_fe_pc_gen.sv"] \
 [file normalize "${origin_dir}/../../bp_fe/src/v/bp_fe_top.sv"] \
 [file normalize "${origin_dir}/../../bp_fe/src/v/bp_fe_icache.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cache/bp_me_cache_slice.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_loopback.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_msg.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_burst_to_lite.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cache/bp_me_cce_to_cache_dma.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_io_cce.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_lite_to_stream.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_src_sel.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/lce/bp_lce.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_lite_to_burst.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_uce.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/lce/bp_lce_cmd.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_inst_ram.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cache/bp_me_cce_to_cache.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_dir.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_dir_segment.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_fsm.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/lce/bp_lce_req.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_me_cce_to_mem_link_bidir.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_fsm_top.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/wormhole/bp_stream_to_lite.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_wrapper.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce_reg.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cache/bp_me_cache_dma_to_cce.sv"] \
 [file normalize "${origin_dir}/../../bp_me/src/v/cce/bp_cce.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_cfg.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_core.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_clint_slice.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_cacc_tile.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_io_link_to_lce.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_cacc_vdp.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_io_tile.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_core_minimal.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_l2e_tile.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_tile.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_sacc_vdp.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_unicore.sv"] \
 [file normalize "${origin_dir}/../../bp_top/src/v/bp_sacc_tile.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_fp_to_rec.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_rec_to_fp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_checker/bp_be_regfile.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_checker/bp_be_scoreboard.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_cacc_complex.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_cacc_tile_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_alu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_arbitrate.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_branch.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_dir_lru_extract.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_dir_tag_checker.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_gad.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_inst_decode.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_inst_predecode.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_inst_stall.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_pending_bits.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_pma.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_spec_bits.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_core_complex.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_fe/src/v/bp_fe_bht.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_fe/src/v/bp_fe_btb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_fe/src/v/bp_fe_instr_scan.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_io_complex.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_io_tile_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_l2e_tile_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_addr_to_cce_id.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_cce_id_to_cord.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_cord_to_id.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_lce_id_to_cord.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_mem_complex.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_common/src/v/bp_mmu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_multicore.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_nd_socket.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_common/src/v/bp_pma.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_sacc_complex.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_sacc_tile_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_tile_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_common/src/v/bp_tlb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bsg_async_noc_link.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_common/src/v/bsg_bus_pack.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_common/src/v/bsg_fifo_1r1w_rolly.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_ptw.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_checker/bp_be_scheduler.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_checker/bp_be_director.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_dcache/bp_be_dcache.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_checker/bp_be_detector.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_calculator/bp_be_csr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_fe/src/v/bp_fe_pc_gen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_fe/src/v/bp_fe_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_fe/src/v/bp_fe_icache.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cache/bp_me_cache_slice.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_loopback.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_msg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_burst_to_lite.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cache/bp_me_cce_to_cache_dma.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_io_cce.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_lite_to_stream.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_src_sel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/lce/bp_lce.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_lite_to_burst.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_uce.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/lce/bp_lce_cmd.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_inst_ram.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cache/bp_me_cce_to_cache.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_dir.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_dir_segment.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_fsm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/lce/bp_lce_req.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_me_cce_to_mem_link_bidir.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_fsm_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/wormhole/bp_stream_to_lite.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_wrapper.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce_reg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cache/bp_me_cache_dma_to_cce.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_me/src/v/cce/bp_cce.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_cfg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_core.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_clint_slice.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_cacc_tile.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_io_link_to_lce.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_cacc_vdp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_io_tile.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_core_minimal.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_l2e_tile.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_tile.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_sacc_vdp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_unicore.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../bp_top/src/v/bp_sacc_tile.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "bp_be_pipe_aux" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/arty_a7_100.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/arty_a7_100.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "bp_be_pipe_aux" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
